version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-laravel-app:latest
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini  # 必要に応じてカスタム設定
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64  # 追加
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: your_user
      PMA_PASSWORD: your_password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
